# Generated by Django 2.0.4 on 2018-04-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='ratings',
            field=models.PositiveSmallIntegerField(max_length=2),
        ),
    ]
