# Generated by Django 2.0.4 on 2018-04-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180411_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='ratings',
            field=models.PositiveSmallIntegerField(max_length=1),
        ),
    ]
