# Generated by Django 2.0.4 on 2018-04-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180411_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='ratings',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
